### ISSUE TITLE
missing module 'migliore_python'

### ISSUE THREAD

**Issue by jschmalz** [armerg/ca1_muscarinic_modulation#1]
I downloaded all of your code and when I ran "m1_model_results.py" I received the following error:
 
Traceback (most recent call last):
  File "m1_model_results.py", line 3, in <module>
    import migliore_python as mig_py
ModuleNotFoundError: No module named 'migliore_python'

Should I be running a different file to generate the results from the paper? 
Could you provide instructions on how to run your code?

Thank you for your time.

**Comment by armerg** [comment]
I've pushed changes that should fix this issue. I've also expanded the README to provide a starting point in understanding what the main scripts do. Let me know if you have questions concerning how the code operates and I'll help out and expand the readme accordingly.
