### ISSUE TITLE
ValueError: 'ca1_muscarinic_modulation' is not in list

### ISSUE THREAD

**Issue by jschmalz** [armerg/ca1_muscarinic_modulation#2]
I re-ran your new code and I received the following error.

Traceback (most recent call last):
  File "m1_model_results.py", line 2709, in <module>
    home_i = path_parts.index('ca1_muscarinic_modulation')
ValueError: 'ca1_muscarinic_modulation' is not in list

**Comment by armerg** [comment]
I changed the code so that this issue should be fixed. Let me know if any other problems arise.
